Your task involves setting up storage components in a Kubernetes cluster. Follow these steps:

Step 1: Create a Storage Class named blue-stc-cka with the following properties:

Provisioner: kubernetes.io/no-provisioner
Volume binding mode: WaitForFirstConsumer
Step 2: Create a Persistent Volume (PV) named blue-pv-cka with the following properties:

Capacity: 100Mi
Access mode: ReadWriteOnce
Reclaim policy: Retain
Storage class: blue-stc-cka
Local path: /opt/blue-data-cka
Node affinity: Set node affinity to create this PV on controlplane .
Step 3: Create a Persistent Volume Claim (PVC) named blue-pvc-cka with the following properties:

Access mode: ReadWriteOnce
Storage class: blue-stc-cka
Storage request: 50Mi
The volume should be bound to blue-pv-cka .



root@controlplane:~$ cat sc.yml 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: blue-stc-cka 
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain # default value is Delete
allowVolumeExpansion: true
mountOptions:
  - discard # this might enable UNMAP / TRIM at the block storage layer
volumeBindingMode: WaitForFirstConsumer
parameters:
  guaranteedReadWriteLatency: "true" # provider-specific

root@controlplane:~$ cat pv.yml 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: blue-pv-cka 
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: blue-stc-cka
  local:
    path: /opt/blue-data-cka
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - controlplane

root@controlplane:~$ cat pvc.yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blue-pvc-cka
spec:
  storageClassName: blue-stc-cka
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  volumeName: blue-pv-cka

  In Kubernetes, both "local path" and "host path" are ways to provide storage from a node’s local filesystem. The difference is mainly in how Kubernetes interprets and binds them.

A "hostPath" volume directly references a directory on the node. It’s simple but tightly coupled to the node. If a pod moves to another node, that directory won't exist there unless explicitly created. It’s mostly used in single-node setups or for testing.

A "local" persistent volume, on the other hand, is more structured. It still uses a directory on the node, but it requires a storage class with "no-provisioner." Importantly, a local PV includes node affinity—it explicitly binds to a specific node. This way, Kubernetes knows that the volume is tied to a particular node and won't schedule the pod elsewhere.